### ISSUE TITLE
dev/log inside user's view

### ISSUE THREAD

**Issue by adripo** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#12]
I tried to use this plugin but it creates a dev/log file inside every user's folder. 
I saw that this file is a link needed to rsyslog in order to log user actions. Is it possible to hide it?
Thanks

**Comment by ryecoaaron** [comment]
Not with the current plugin. Why do you want to hide it?

**Comment by adripo** [comment]
Because I see that folder every time I connect via sftp.
What will happen if I share a folder named log?

**Comment by ryecoaaron** [comment]
I haven’t tried. Are you planning on doing that?  I will make it optional.

**Comment by adripo** [comment]
It could happen. I just don't understand exactly why the log file is visible from sftp view.
Can you explain me better, please?

**Comment by subzero79** [comment]
The file is a socket. The session is chrooted, then the socket is mount bind because otherwise there would not be logging. I don’t know if the socket name sftp is expecting is hard coded to “log” is this really an issue ? If is hard coded then no, you cannot have a folder named log in the base chroot.

**Comment by adripo** [comment]
Okay, I got it.
Maybe you can consider hiding dev/log from user view as a feature request for next versions.
Thank you

**Comment by ryecoaaron** [comment]
5.0.6 is in the repo with the option to disable logging.  It won't cleanup the log socket if created previously.
