### ISSUE TITLE
omv-sftp "PermitRootLogin" is set "yes". This need to fix.

### ISSUE THREAD

**Issue by whitecloudy** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#15]
I found out that if OMV_SFTP_PERMITROOTLOGIN is not set for some reasons(don't know why though), omv-sftp's PermitRootLogin setting becomes "yes".

I think this problem should be fixed for safty.

**Comment by whitecloudy** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-sftp/pull/16#issue-1103443979

I made pull request about this problem. Don't know this is enough or not though.....

**Comment by ryecoaaron** [comment]
Having root enabled is not a safety problem if you have a strong password.  Running on a non-default port and not exposing to the internet help even more.  If you want to disable root on your system, please set the environment variable that you have listed.  I am not going to change the default behavior of the plugin because this will break the plugin for some existing users.

**Comment by nailug** [comment]
Thanks for the plugin.
That was very hard to find that env variable OMV_SFTP_PERMITROOTLOGIN exists.
As PermitRootLogin yes is now by default in /etc/ssh/omv_sftp_config, and you don't want to change this (what I understand), make it more clear on how to set OMV_SFTP_PERMITROOTLOGIN=no; or add it to the omv parameters please.

**Comment by ryecoaaron** [comment]
> That was very hard to find that env variable OMV_SFTP_PERMITROOTLOGIN exists.

omv-env list will show you all OMV environment variables.  You can also see them here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-sftp/blob/master/srv/salt/omv/deploy/sftp/files/omv_sftp_config.j2

> make it more clear on how to set OMV_SFTP_PERMITROOTLOGIN=no

Once you have the variable name, the OMV documentation is here - https://docs.openmediavault.org/en/stable/various/advset.html

> or add it to the omv parameters please.

I will consider adding it to the plugin but it would be in the OMV 8 version.

**Comment by nailug** [comment]
Just for info, This maybe something to fix: in /srv/salt/omv/deploy/sftp/files/omv_sftp_config.j2 :

salt['pillar.get']('default:OMV_SFTP_PERMITROOTLOGIN', 'no') looks in Pillars Salt value of OMV_SFTP_PERMITROOTLOGIN
But condition {{ 'yes' if rootLogin else 'no' }} in Jinja does not always work as intended if rootLogin is a string.
Si rootLogin is 'no' (string), then 'yes' if rootLogin else 'no' will send… yes, because any string not empty is evaluated at True in Jinja.

Do you think : PermitRootLogin {{ 'yes' if rootLogin == 'yes' else 'no' }} can be better?

**Comment by ryecoaaron** [comment]
Other than the fact that this will change once the field is on the plugin's form, are you saying the plugin should handle a non-boolean string in the environment variable?

**Comment by nailug** [comment]
You're right. What do you think of :
{{ 'yes' if OMV_SFTP_PERMITROOTLOGIN else 'no' }}

**Comment by ryecoaaron** [comment]
I think either one is fine but I would probably use:

 {{ 'yes' if OMV_SFTP_PERMITROOTLOGIN | to_bool else 'no' }}

**Comment by nailug** [comment]
yes, thanks.
Anyway, to let you know, I didnot succeed in OMV7 to set PermitRootLogin no in /etc/shh/omv_sftp_config.
The "omv-env set -- OMV_SFTP_PERMITROOTLOGIN no" works, and is well integrated to the variables but the /etc/ssh/omv_sftp_config PermitRootLogin remains yes, no matter what I do.

The only way I found to get PermitRootLogin no is to create a :
/srv/salt/omv/deploy/sftp/999_force_no_root.sls
force_no_root_login:
  file.replace:
    - name: /etc/ssh/omv_sftp_config
    - pattern: '^PermitRootLogin .*'
    - repl: 'PermitRootLogin no'
    - backup: False

an then add it to init.sls

**Comment by ryecoaaron** [comment]
No need to add a file.  I fixed the logic and pushed 7.0.6 to the repo.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-sftp/commit/9ad13d9b6800595182a75b57502f46886f2ecd40

**Comment by nailug** [comment]
Thank you very much
