### ISSUE TITLE
Group permissions

### ISSUE THREAD

**Issue by BenMcLean** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#18]
This plugin should allow permissions and access to be managed for user groups instead of individual users. I shouldn't have to configure an individual folder/user pair for every user and every folder and make sure every individual user has individual permissions to every individual folder. It should be set up once per folder for the whole group.

This is such a huge problem for me that I'm looking into a third party docker-based solution for sftp instead.

**Comment by ryecoaaron** [comment]
As i mentioned on the forum, the plugin would almost have to be completely rewritten to use groups instead of users.  I'm not sure the chroot functionality would be possible to implement which is a primary reason for the sftp plugin existing.

https://forum.openmediavault.org/index.php?thread/47455-sftp-for-groups/&postID=347975#post347975

**Comment by BenMcLean** [comment]
I just want to say: thanks for the help on the forums and sorry I forgot to close this issue before now since, from what I gather, the sftp plugin pretty much can't be rewritten to work the way I was requesting, although the documentation for all of the software involved could be a lot clearer than it was.
